### ISSUE TITLE
Determination du type de document pour les marketplaces

### ISSUE THREAD

**Issue by clementbiron** [OpenTermsArchive/france-declarations#27]
Bonjour,

Je chercher à déterminer le type de ce [document](https://static.cedex.it.showroomprive.com/v3/0/docs/CGV/Showroomprive.com_CGV_Marketplace.pdf) pour Showroomprive.com

Il s'agit des conditions générale de vente de la marketplace. 

Une piste ?

A savoir, nous enregistrons déjà un document de type `Commercial Terms`, disponible à cette adresse  `https://www.showroomprive.com/contratcgv.aspx`

**Comment by clementbiron** [comment]
Je rencontre le même problème de choix de type de document pour  Cdiscount Marketplace : `https://i2.cdscdn.com/resources/imagesok/cgu/mkp/cgu_acheteurs_mp_cdiscount.pdf`

**Comment by clementbiron** [comment]
Pareil pour `https://www.laredoute.fr/popupvendortermsconditions.aspx`

**Comment by MattiSG** [comment]
Pour moi les marketplaces devraient être en [Commercial Terms](https://github.com/ambanum/OpenTermsArchive/blob/master/src/archivist/services/documentTypes.json#L65-L71), qui encadrent le _business or commercial usage_ des _commercial partners, content creators in a platform_.

Spontanément, j'aurais dit que les CGV d'un service de vente en ligne sont ses conditions d'utilisation du service (puisque le service est la vente en ligne), mais j'ai compris de notre échange avec l'UFC ce matin qu'il y avait souvent aussi des CGUs en parallèle des CGVs, qui encadrent l'usage du site lui-même.

J'en conclus qu'il faudrait un nouveau type pour les CGV (et donc renommer a posteriori tous les Commercial Terms actuels dans ce nouveau type 😬 ).

Je m'interroge à quel point ce nouveau type CGV devrait rendre obsolète (i.e. remplacer en le recouvrant) le type [`Seller Warranty`](https://github.com/ambanum/OpenTermsArchive/blob/master/src/archivist/services/documentTypes.json#L149).

**Comment by MattiSG** [comment]
Je serais d'avis de faire valider cette proposition, et notamment la différence entre le cas d'usage marketplace vs usage type annonceurs Facebook ou créateurs de contenu monétisé sur YouTube, par les juristes de l'UFC 🙂

**Comment by clementbiron** [comment]
Ok merci pour ton retour, je suis 100% aligné, discutons en avec l'UFC.

**Comment by MattiSG** [comment]
Pardon, j'ai oublié de débriefer ici, mais j'ai confirmé cela vendredi dernier !

Il y aurait donc a priori, à traduire et améliorer évidemment :

### Marketplace

writer: marketplace provider
audience: end buyer
subject: CGV on goods sold by third parties

### CGV

writer: paid-for goods or service provider
audience: end buyer
subject: warranty, delivery, return of goods or services bought through a moneteray transaction

**Comment by MattiSG** [comment]
Closed via https://github.com/ambanum/OpenTermsArchive/pull/851
