### ISSUE TITLE
Add General Conditions of Sale document type

### ISSUE THREAD

**Issue by MattiSG** [OpenTermsArchive/france-declarations#350]
Following #339, a new document type has been introduced to this instance (https://github.com/ambanum/OpenTermsArchive/issues/795). It has been defined in https://github.com/ambanum/OpenTermsArchive/pull/806. However, the dependencies in this instance have not been updated to take it into account, thus making it unusable for validation. I believe this should just be a lockfile update, but would prefer that someone who has enough availability to check the consequences handles this update 🙂

**Comment by MattiSG** [comment]
@ndpnt @clementbiron can one of you handle this? 🙂

**Comment by Ndpnt** [comment]
This PR https://github.com/OpenTermsArchive/france-declarations/pull/352 should fix the issue, no?

**Comment by clementbiron** [comment]
Yes,  tests are passed on the CI for https://github.com/OpenTermsArchive/france-declarations/pull/316 and https://github.com/OpenTermsArchive/france-declarations/pull/299
