### ISSUE TITLE
Investiguer les changements d'Alibaba

### ISSUE THREAD

**Issue by MattiSG** [OpenTermsArchive/france-declarations#353]
Sur https://github.com/OpenTermsArchive/france-versions/commit/386fc97096a06823ef00cb8933a61208a6f403ab et https://github.com/OpenTermsArchive/france-versions/commit/0bae383e4f7a58f686d6792edb04c1c69d6b837b, des changements massifs d'espaces et des remplacements de gras par des retours à la ligne sont observables. En l'absence d'accès aux snapshots, je ne peux pas investiguer leur origine. S'agit-il d'un filtrage inadapté ? D'un problème d'encodage ?

**Comment by MattiSG** [comment]
À nouveau sur https://github.com/OpenTermsArchive/france-versions/commit/153d86e3c0a3d3e6af0e8578e3e5f52e8cc0ac4c et https://github.com/OpenTermsArchive/france-versions/commit/652e63133897c8ff6982cad3139420c3c39e5835.

**Comment by clementbiron** [comment]
Il semblerait que les documents d'Alibaba utilise un coup des espaces insécables, un coup des espaces 'normaux'.

Je viens d'ouvrir une PR pour corriger ce problème : https://github.com/OpenTermsArchive/france-declarations/pull/427
